version: '3.9'

services:
  backend:
    container_name: backend
    build: ./backend
    restart: unless-stopped
    ports:
      - "5000:5000"
    environment:
      - CLIENT_ORIGIN=$CLIENT_ORIGIN
    networks:
      - driverbridge

  frontend:
    depends_on:
      - backend
    build:
      context: ./frontend
      # args:
      #   - REACT_APP_API_BASE_URL=$CLIENT_API_BASE_URL
    container_name: frontend
    ports:
      - "80:80"
    networks:
      - driverbridge

networks:
  driverbridge:
    driver: bridge

volumes:
  node_modules:  