apiVersion: v1
kind: Namespace
metadata:
  name: website

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginxforwebsite
        image: nginx
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: nginxforwebsite
  labels:
    app: nginx
    team: deployment
  annotations:
    Deployment: Satria dan Ahda
    Roadmap: Satria dan Reza
spec:
  selector:
    app: nginx
  ports:
  - name: http
    port: 80
    targetPort: 80

